#use to through the exception forcefully

a=5
if (a>2):
 raise Exception('a should not exceed 2')
